Construct database models
cuappdev/eatery-backend pull request #144
Opened 2019-10-18 03:41 UTC by yuna878

## Overview

Construct database models as a first step to implement centralized data storage.

## Changes Made

- Create connection to SQLite database
- Construct database models
  - These models are inconsistent with GraphQL schema because we want to store data in a logical manner rather than mirroring the data structure that Cornell Dining gives. This means we need to refactor current parsing methods to : 1) parse Cornell Dining data and store to db 2) query desired data from db and format to match GraphQL schema.
  - All the models extend `Base` class so that tables are able to reference other tables with relationship.

## Test Coverage

Wrote up a short script to test that tables can be generated easily with models and that schemas are created correctly

Script:
<img width="419" alt="Screen Shot 2019-10-17 at 10 54 36 PM" src="https://user-images.githubusercontent.com/36527727/67064063-0d4a9e00-f137-11e9-94a3-e03a9085d2a4.png">

Result:
<img width="490" alt="Screen Shot 2019-10-17 at 10 55 16 PM" src="https://user-images.githubusercontent.com/36527727/67064071-16d40600-f137-11e9-9a55-31a9b9757f85.png">

## Next Steps

Future PRs should address the refactoring of parsing functions as mentioned above. When transition to using a database is done, we will have to write up a cron job to run the updates to database.

2019-10-18 13:47 UTC, young-k requested changes
Minor changes, but looks good!

2019-10-18 13:47 UTC, young-k commented on .gitignore
> +data.db
I'm pretty certain that the naming convention for sqlite files is `.sqlite3`

2019-10-18 13:47 UTC, young-k commented on src/db_models/CampusHoursBase.py
> +    id = Column(Integer, nullable=False, primary_key=True)
It's normally convention to have `id` always be the first field of any model, but it's up to @meganle

2019-10-18 13:47 UTC, young-k commented on src/db_models/CollegetownHoursBase.py
> +        return table_name
Could there be a base class that defines this `tablename` function that `CampusHoursBase` and `CollegetownHoursBase` both extend from?

2019-10-18 13:47 UTC, young-k commented on src/db_models/MenuBase.py
> +        return table_name
same comment here

2019-10-18 13:47 UTC, young-k commented on src/db_models/SwipeDataBase.py
> +        return table_name
and again here!

2019-10-19 16:19 UTC, meganle approved these changes
Looks good!! 🔥

2019-10-20 01:08 UTC, orkosinha approved these changes
lgtm!!

2019-10-20 16:36 UTC, meganle commented on requirements.txt
> +graphene-sqlalchemy==2.2.2
do we need?

2019-10-23 16:48 UTC, young-k approved these changes
lgtm

2019-10-23 20:32 UTC, merged