Concat date with start & end times
cuappdev/eatery-backend pull request #22
Opened 2018-11-11 17:36 UTC by cswenberg

Concat date with start and end times to distinguish when operating hours extend into the next day.  Standardization of hours is as follows

isodate -> YYYY-MM-DD
time      ->  hh:mm<am or pm>

Now new with concat:
start_time -> isodate:time
end_time  -> isodate:time

2018-11-11 18:23 UTC, young-k requested changes
Some cool pythonic changes we can implement to have cleaner code

2018-11-11 18:23 UTC, young-k commented on data.py
> +  new_end = end_date + ':' + end_hour + ':' + end_minute
format string for this line and the above line as well

2018-11-11 18:23 UTC, young-k commented on data.py
> +  end_date = start_date
what's the point of this?

2018-11-11 18:23 UTC, young-k commented on data.py
> +  end_hour = '0' + end_hour if len(end_hour) < 2 else end_hour
replace with:
`end_hour = end_hour.rjust(2, "0")`

@kq-li @alanna-zhou @meganle lmk is this nifty or is this nifty

2018-11-11 18:23 UTC, young-k commented on data.py
> +  [end_hour, end_minute] = end_time.split(':')
you can omit the `[]`, so `end_hour, end_minute = end_time.split(':')`

2018-11-11 18:23 UTC, young-k commented on data.py
> +    [year, month, day] = start_date.split('-')
same here as well, the `[]` can be omitted

2018-11-11 18:23 UTC, young-k commented on data.py
> +  if (int(end_hour) < int(start_hour) or end_hour == '12') and end_minute[-2:] == 'am':
`end_minute.endswith('am')`

2018-11-11 23:12 UTC, young-k approved these changes
LGTM

2018-11-11 23:12 UTC, merged

2018-11-12 02:00 UTC, alanna-zhou commented on data.py
> +  end_hour = '0' + end_hour if len(end_hour) < 2 else end_hour
wau so nifty where did you learn this from

2018-11-12 02:08 UTC, young-k commented on data.py
> +  end_hour = '0' + end_hour if len(end_hour) < 2 else end_hour
i read all of `python` documentation when i was preparing for interviews hahAA

2018-11-12 02:14 UTC, kq-li commented on data.py
> +  new_end = end_date + ':' + end_hour + ':' + end_minute
make sure to use python 3 [f-strings](https://realpython.com/python-f-strings/)!

2018-11-12 02:14 UTC, kq-li commented on data.py
> +  end_hour = '0' + end_hour if len(end_hour) < 2 else end_hour
spending your time wisely i see

2018-11-12 02:24 UTC, meganle commented on data.py
> +  end_hour = '0' + end_hour if len(end_hour) < 2 else end_hour
wOw so nifty