Add query to check for "favorite" food items
cuappdev/eatery-backend pull request #239
Opened 2021-03-31 00:10 UTC by raahimenon

## Overview

Frontend can pass in a list of "favorites" as strings; any food in the list will be marked as a favorite in the response body.

## Changes Made
Favorites were added to the resolver for campus eateries and eateries (which both link to the same function). To use this, frontend can add a `(favorites: [LIST OF STRINGS])` to their query after `eateries` or `campusEateries`. 

## Test Coverage
Manual testing.

## Next Steps (delete if not applicable)
Add a route to store favorites along with netIDs for users that are signed in to the app.

2021-03-31 01:42 UTC, grebneerg requested changes
Once you address hound's comments this should be good.

2021-03-31 01:42 UTC, grebneerg commented on src/gql_parser/campus_eatery.py
> +def get_campus_eateries(eatery_id, favorites=[]):
why is python like this

2021-03-31 05:19 UTC, alanna-zhou approved these changes
hound needs to calm down but u are very cool thanku

2021-03-31 05:19 UTC, alanna-zhou commented on src/schema.py
> +    def resolve_eateries(self, info, eatery_id=None, favorites=[]):
lol hound u need to calm down

2021-04-03 22:12 UTC, grebneerg approved these changes
Looks good

2021-04-03 22:12 UTC, merged