Order data updating
cuappdev/eatery-backend pull request #56
Opened 2018-12-10 17:44 UTC by cswenberg

Allows querying campus eateries while we fetch from yelp.

2018-12-10 18:04 UTC, meganle approved these changes
Amazing, nice work!

2018-12-10 19:16 UTC, young-k commented on src/data.py
> +    print('[{0}] Updating collegetown'.format(datetime.now()))
i don't think you need `{0}` if it's just 1, you can just have `{}`

2018-12-10 19:16 UTC, young-k commented on src/data.py
> +    Data.update_collegetown(collegetown_eateries)
rename to `update_collegetown_data`

2018-12-10 19:18 UTC, young-k requested changes
Meant to request changes whoops

2018-12-10 19:18 UTC, young-k commented on src/data.py
>      statics_json = requests.get(STATIC_EATERIES_URL).json()
`static_json`

2018-12-11 00:23 UTC, ilikesymmetry commented
changes made @young-k

2018-12-11 03:17 UTC, young-k approved these changes

2018-12-11 03:59 UTC, merged